# This is a generated file. Not intended for manual editing.
services:
  hablechat.api:
    build:
      context: "/home/fernando/Documentos/Desktop/HablaChat/api"
      dockerfile: "src/HableChat.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/HableChat.API.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "hablechat.api:dev"
    ports: []
    volumes:
    - "/home/fernando/.nuget/packages:/home/app/.nuget/packages"
    - "/home/fernando/Documentos/Desktop/HablaChat/api/src/HableChat.API:/app:rw"
    - "/home/fernando/Documentos/Desktop/HablaChat/api:/src:rw"
    working_dir: "/app"
